// Mavzularning ro'yxat ko'rinishidagi standart nomlari (darslik uslubida, belgilarsiz).
// Kalit: `g{sinf}_c{chorak}`, qiymat: shu chorakdagi bloklar tartibidagi nomlar.
// curriculum.json skript orqali qayta yaratiladi, shuning uchun nomlar shu yerda alohida saqlanadi.
// Nomni o'zgartirish uchun shu fayldagi tegishli qatorni tahrirlash kifoya.
export const TOPIC_TITLES = {
  g1_c1: [
    "Narsalarning shakli, rangi va o'lchami. Kattaliklarni taqqoslash. Fazoviy munosabatlar",
    "Narsalarni sanash. 1 dan 9 gacha sanoq",
    "Yassi va hajmli geometrik shakllar",
    "Vaqt bo'yicha ketma-ketlik. Hafta kunlari",
    "Narsalar guruhlarini taqqoslash. Teng va teng emas. Ko'p, kam, shuncha",
    "10 ichidagi sonlar. Sanoq tartibi. Oldingi va keyingi son",
    "10 ichida qo'shish va ayirish amallari. Yig'indi va ayirma",
    "Sonlarni taqqoslash. Katta, kichik va teng",
    "1, 2, 3, 4, 5 sonlari va raqamlari. Sonning tarkibi",
    "Butun va qism. Son nurida qo'shish va ayirish",
    "6, 7, 8, 9 sonlari va raqamlari. Sonning tarkibi",
    "0 soni. 10 soni va uning tarkibi",
    "10 ichida sonlarni taqqoslash. O'sish va kamayish tartibi. Natural sonlar",
    "Juft va toq sonlar",
    "Nuqta. To'g'ri va egri chiziq. Kesma. Siniq chiziq",
    "Qo'shish hadlari. Qo'shiluvchi va yig'indi. Ayirish hadlari. Kamayuvchi, ayriluvchi va ayirma",
    "Noma'lum qo'shiluvchini topish. Noma'lum kamayuvchi va ayriluvchini topish",
    "Qo'shish va ayirish orasidagi bog'lanish. Qo'shishning o'rin almashtirish xossasi",
    "10 ichida qo'shish jadvali",
    "Sonli ifoda va uning qiymati. Harfiy ifodalarni taqqoslash",
    "I chorak bo'yicha takrorlash. Yakuniy test",
  ],
  g1_c2: [
    "11 dan 20 gacha sonlar. Ikki xonali son. O'nlik va birlik",
    "11 dan 20 gacha sonlarning tarkibi. Juft va toq sonlar",
    "20 ichida sonlarni taqqoslash",
    "Qavslar. Amallar tartibi",
    "Bir xonali sonlarni o'nlikdan o'tib qo'shish",
    "O'nlikdan o'tib ayirish",
    "Yaxlit o'nliklar. O'ntalab sanash. Yaxlit o'nliklarni qo'shish va ayirish",
    "21 dan 100 gacha sonlar. O'qilishi va yozilishi. Xona birliklari",
    "Ikki xonali sonlarni taqqoslash va tartiblash",
    "Ikki xonali sonlarni xonadan o'tmasdan qo'shish",
    "Ikki xonali sonlarni xonadan o'tmasdan ayirish",
    "Qo'shish va ayirish orasidagi bog'lanish",
    "Bir nechta sonni qo'shish. Qo'shishning guruhlash xossasi",
    "Tarkibli ifodalar. Qavsli ifodalarda amallar tartibi",
    "II chorak bo'yicha takrorlash. Yakuniy test",
  ],
  g1_c3: [
    "Masala va uning tarkibi. Shart, savol, yechim va javob. Sodda masalalar",
    "Butunni topishga doir masalalar",
    "Qismni topishga doir masalalar",
    "Sonni bir necha birlik orttirish va kamaytirishga doir masalalar",
    "Ayirmali taqqoslashga doir masalalar",
    "Murakkab ifodalar. Amallar tartibi",
    "Tarkibli masalalar. Mantiqiy masalalar",
    "Masalalar yechish bo'yicha takrorlash",
    "Uzunlik. Santimetr. Kesma va uning uzunligi",
    "Detsimetr. Uzunlik birliklari orasidagi munosabat",
    "Ko'pburchak tomonlarining uzunliklari yig'indisi",
    "Massa. Kilogramm",
    "Sig'im. Litr",
    "Kattaliklar va ularning xossalari",
    "III chorak bo'yicha takrorlash. Yakuniy test",
  ],
  g1_c4: [
    "Kesmani o'lchash va chizish. Siniq chiziq uzunligi",
    "Ko'pburchak va uning perimetri. Kvadrat va to'g'ri to'rtburchak perimetri",
    "To'g'ri to'rtburchak va kvadrat. To'g'ri, o'tkir va o'tmas burchak",
    "Burchak turlari. To'rtburchak turlari",
    "Teng shakllar. Qismlardan shakl tuzish",
    "Simmetriya o'qi. Simmetrik shakllar",
    "Hajmli shakllar. Kub, shar, silindr, konus, piramida va prizma",
    "Tenglik va tengsizliklar",
    "Sonli va harfiy ifodalar. Harfiy ifodaning qiymati",
    "Qo'shishning o'rin almashtirish va guruhlash xossalari. O'zgaruvchili tengsizliklar",
    "Tenglama. Tenglamani yechish va tekshirish. Masalalarni tenglama yordamida yechish",
    "Kesmalar uzunliklari orasidagi tenglik va tengsizlik",
    "Yillik takrorlash",
  ],
  g2_c1: [
    "100 ichidagi sonlarni takrorlash. Qo'shish, ayirish va taqqoslash",
    "Nuqta, to'g'ri va egri chiziq. Nur va kesma. Siniq chiziq va perimetr",
    "Sonli va harfiy ifoda. Ifodaning qiymati",
    "Uzunlik birliklari. O'zaro teskari masalalar",
    "Xona birliklari. Xona qo'shiluvchilari. 100 ichida qo'shish va ayirish",
    "Yaxlit songacha to'ldirib qo'shish. Yaxlit sondan ayirish",
    "To'liq o'nlik hosil qilib qo'shish",
    "Ikki xonali sondan ayirish. Sondan yig'indini ayirish",
    "Xonadan o'tib qo'shish",
    "Xonadan o'tib ayirish",
    "Oraliq takrorlash",
    "Ikki xonali sonlarni qo'shish. Ustun shaklida qo'shish",
    "Ikki xonali sonlarni ayirish",
    "Ustun shaklida qo'shish va ayirish. Guruhlash xossasi. Og'zaki hisoblash usullari",
    "Yig'indidan sonni ayirish",
    "Sondan yig'indini ayirish",
    "Qo'shish va ayirishga doir masalalar. Teskari masalalar",
    "Jadval va diagrammalarni o'qish",
    "I chorak bo'yicha takrorlash. Venn diagrammasi. Yakuniy test",
  ],
  g2_c2: [
    "Uch xonali sonlar. Yuzlar xonasi. O'qilishi va yozilishi",
    "Uch xonali sonning xona qo'shiluvchilari",
    "Uch xonali sonlarni taqqoslash va tartiblash",
    "Uch xonali sonlarni qo'shish",
    "Uch xonali sonlarni ayirish",
    "Uch xonali sonlarni qo'shish va ayirishga doir masalalar",
    "Oraliq takrorlash",
    "Uzunlik birliklari. Metr, detsimetr va santimetr",
    "Millimetr. Siniq chiziq uzunligi. Ko'pburchak perimetri",
    "Qo'shish va ayirish orasidagi bog'lanish. Amallarni tekshirish",
    "Tenglamalar. Noma'lum qo'shiluvchi, kamayuvchi va ayriluvchini topish",
    "Vaqt birliklari. Soat va minut",
    "Vaqtga doir masalalar",
    "II chorak bo'yicha takrorlash. Yakuniy test",
  ],
  g2_c3: [
    "To'g'ri chiziq, nur va kesma. Tekislik",
    "Burchak va uning turlari",
    "To'g'ri to'rtburchak va kvadrat",
    "To'g'ri burchak yasash. Katakli qog'ozda shakllar chizish",
    "Yuz tushunchasi. Shakl yuzini kataklar yordamida topish",
    "Yuz o'lchov birliklari",
    "Geometriya bo'yicha takrorlash",
    "Ko'paytirish. Ko'paytirish hadlari. O'rin almashtirish xossasi. To'g'ri to'rtburchak yuzi",
    "1 ga va 2 ga ko'paytirish jadvali",
    "Bo'lish. Bo'lish hadlari. 2 ga bo'lish",
    "Juft va toq sonlar",
    "3 ga ko'paytirish va bo'lish",
    "4 ga ko'paytirish va bo'lish",
    "5 ga ko'paytirish va bo'lish",
    "Sonni bir necha marta orttirish va kamaytirish",
    "Ko'paytirish va bo'lish bo'yicha takrorlash",
    "6 ga ko'paytirish va bo'lish",
    "7 ga ko'paytirish va bo'lish",
    "8 ga ko'paytirish va bo'lish",
    "9 ga ko'paytirish va bo'lish",
    "Ko'paytirish jadvali. Ko'paytirish va bo'lish orasidagi bog'lanish",
    "Bo'luvchilar va karralilar",
    "III chorak bo'yicha takrorlash. Yakuniy test",
    "Mantiqiy masalalar",
  ],
  g2_c4: [
    "Ko'paytirishning o'rin almashtirish va guruhlash xossalari",
    "1 va 0 bilan ko'paytirish va bo'lish",
    "Qavssiz ifodalarda amallar tartibi",
    "Qavsli ifodalarda amallar tartibi",
    "Tenglamalar. Tenglama tuzish, yechish va tekshirish",
    "Masalalar yechish. Oraliq takrorlash",
    "10 ga va 100 ga ko'paytirish va bo'lish",
    "Yaxlit sonlarni ko'paytirish",
    "Yaxlit sonlarni bo'lish",
    "Yig'indini songa ko'paytirish. Taqsimot xossasi",
    "Ikki xonali sonni bir xonali songa ko'paytirish",
    "Hajmli shakllar. Kub va to'g'ri burchakli parallelepiped. Hajm",
    "Aylana va doira. Radius va diametr",
    "Yillik takrorlash",
    "Mantiqiy topshiriqlar",
  ],
  g3_c1: [
    "Takrorlash. Ko'p xonali sonlar. Qo'shish va ayirish xossalari",
    "Takrorlash. Uzunlik birliklari",
    "Takrorlash. Ko'paytirish va bo'lish. 0 va 1 sonlarining xossalari",
    "Takrorlash. Vaqt birliklari. To'g'ri to'rtburchak perimetri va yuzi",
    "Ko'p xonali sonlar. Sinflar va xonalar. Rim raqamlari",
    "Millionlar sinfi. Ko'p xonali sonlarni o'qish va yozish",
    "Ko'p xonali sonlarni taqqoslash. Xona qo'shiluvchilari",
    "Ko'p xonali sonlarni ustun shaklida qo'shish. Gektar",
    "Ko'p xonali sonlarni ustun shaklida ayirish",
    "Qo'shish va ayirishning qulay usullari. Amallar tartibi",
    "Oraliq takrorlash",
    "10 ga, 100 ga va 1000 ga ko'paytirish va bo'lish",
    "Ko'p xonali sonni bir xonali songa ko'paytirish",
    "Ko'p xonali sonlarni ko'paytirish. Grafiklarni o'qish",
    "Ikki xonali va uch xonali songa ko'paytirish",
    "Nol bilan tugaydigan sonlarni ko'paytirish. Muntazam ko'pburchak",
    "Aralash amallarga doir masalalar",
    "Narx, miqdor va qiymat. Masalalar",
    "Vaqt birliklari. Soat, minut va sekund",
    "I chorak bo'yicha takrorlash. Yakuniy test",
  ],
  g3_c2: [
    "Yig'indini songa bo'lish",
    "Qoldiqli bo'lish. Qoldiqli bo'lishni tekshirish",
    "Burchak shaklida bo'lish. To'liqsiz bo'linuvchi",
    "Amallar tartibi. Qoldiqli bo'lishga doir mashqlar",
    "Bo'linmada nol. Nol bilan tugaydigan sonlarni bo'lish",
    "Bo'lishga doir masalalar",
    "Oraliq takrorlash",
    "Ikki xonali va uch xonali songa bo'lish",
    "Bo'luvchilar va karralilar",
    "Amaliy mashqlar. Rim raqamlari. Vaqt va massa birliklari",
    "Kesmani teng bo'laklarga bo'lish. To'g'ri to'rtburchak perimetri",
    "Muntazam shakllar perimetri. Simmetriya o'qi",
    "Yuz birliklari. Ulushlar. Murakkab shakllar yuzi",
    "II chorak bo'yicha takrorlash. Yakuniy test",
    "Venn diagrammasi. Sehrli kvadrat",
  ],
  g3_c3: [
    "Massa birliklari. Kilogramm, gramm, tonna va sentner",
    "Uzunlik birliklari va ular orasidagi bog'lanish",
    "Yuz birliklari. Gektar va ar. Masalalar",
    "Hajm birliklari. Litr. Masalalar",
    "Oraliq takrorlash",
    "Shakl yuzini paletka yordamida topish",
    "To'g'ri burchakli parallelepiped va kub. Yoqlari, qirralari va uchlari",
    "Kubning yoyilmasi. To'g'ri burchakli parallelepipedning yoyilmasi. Sirt yuzi",
    "Aylana va doira. Radius va diametr. Sirkul bilan aylana chizish",
    "Doirani teng bo'laklarga bo'lish. Doiraning ulushlari",
    "Ulushlar. Sonning ulushini topish",
    "Oraliq takrorlash",
    "Parallel va perpendikular to'g'ri chiziqlar",
    "Koordinata nuri. Nuqtaning koordinatasi",
    "Tenglik, tengsizlik, tenglama va ifoda. Sonlar nurida harakat",
    "Sodda tenglamalar. Tengsizlik yechimlari",
    "Koordinata burchagi. Nuqtani yasash",
    "O'qqa nisbatan simmetriya. Simmetrik shakllar",
    "Tarkibli tenglamalar",
    "III chorak bo'yicha takrorlash. Yakuniy test",
  ],
  g3_c4: [
    "Perimetr, yuz va hajm formulalari",
    "Qoldiqli bo'lish formulasi. Qadimiy o'lchov birliklari. Amaliy masalalar",
    "Tezlik, vaqt va masofa",
    "Harakatga doir masalalar",
    "Narx, miqdor va qiymat",
    "Qiymatga doir masalalar",
    "Ish unumdorligi, vaqt va ish hajmi. Masalalar",
    "Oraliq takrorlash",
    "To'plam va uning elementlari. Teng to'plamlar. Qism to'plam",
    "Eyler-Venn diagrammasi. Qism to'plam. Bo'sh to'plam",
    "To'plamlarning kesishmasi va birlashmasi",
    "Venn diagrammasiga doir masalalar. Rost va yolg'on mulohazalar",
    "Oraliq takrorlash",
    "Yillik takrorlash. Ko'p xonali sonlar va amallar",
    "Yillik takrorlash. Masalalar, geometriya va ulushlar",
    "Venn diagrammasi va kombinatorikaga doir masalalar",
  ],
  g4_c1: [
    "Ko'p xonali sonlar. Xona birliklari va taqqoslash",
    "Amallarning hadlari. Noma'lum hadni topish",
    "Harakat va ish unumdorligiga doir masalalar",
    "Tenglama va tengsizliklar",
    "Koordinata nuri va koordinata burchagi. Takrorlash",
    "Vaqt va uning o'lchov birliklari",
    "Yuz va perimetr",
    "Bo'luvchilar va karralilar",
    "Bo'linish alomatlari",
    "Bo'linish va karralilarga doir masalalar",
    "To'plamlar. Ma'lumotlarni taqdim etish",
    "O'rta arifmetik",
    "Chastota",
    "O'rtacha qiymatga doir amaliy masalalar",
    "Parallel va perpendikular to'g'ri chiziqlar",
    "Koordinata nuri va koordinata burchagi",
    "Ustunli va chiziqli diagrammalar",
    "Chamalash. Grafiklar va masalalar",
    "Tadqiqot va so'rovnoma. Venn diagrammasi",
    "Algoritmlar va blok-sxemalar",
    "Xaridga doir ko'p bosqichli masalalar",
    "I chorak bo'yicha takrorlash. Yakuniy test",
  ],
  g4_c2: [
    "Ko'p xonali sonlar va harakatga doir masalalar. Takrorlash",
    "Sonlar nuri. Shkala. Nuqtalar orasidagi masofa",
    "Shakl yuzini kataklar yordamida topish",
    "Yo'l, vaqt va tezlik",
    "Bir-biriga qarab harakatlanish",
    "Qarama-qarshi yo'nalishda harakatlanish",
    "Quvib yetish harakati",
    "Biri kechikib chiqqan harakatga doir masalalar",
    "Aniq va taqribiy qiymatlar",
    "Sonlarni o'nliklar va yuzliklargacha yaxlitlash",
    "Ortig'i va kami bilan yaxlitlash",
    "Qiymatlarni chamalash",
    "Hisoblashning qulay usullari",
    "Shakl yuzini kataklar va paletka yordamida hisoblash",
    "Ko'pburchak perimetriga doir masalalar",
    "Amaliy geometrik masalalar",
    "II chorak bo'yicha takrorlash. Yakuniy test",
  ],
  g4_c3: [
    "Bo'lish. Qoldiqsiz va qoldiqli bo'lish",
    "Ulush. Sonning qismini topish",
    "Kattaliklarning qismlari",
    "To'g'ri, noto'g'ri va aralash kasrlar",
    "Kasrlarning sonlar nurida tasvirlanishi",
    "Noto'g'ri kasrni aralash kasrga aylantirish. Aralash kasrni noto'g'ri kasrga aylantirish",
    "Kasrlarni taqqoslash",
    "Uzunlik o'lchov birliklariga doir masalalar. Dyuym, fut va yard",
    "Kasrlarni qo'shish va ayirish",
    "Aralash kasrlarni qo'shish va ayirish",
    "Birdan kasrni ayirish",
    "Butun sondan kasrni ayirish",
    "Kasrni natural songa ko'paytirish",
    "Kasrlarga doir masalalar",
    "O'nli kasrlar. O'qilishi va yozilishi",
    "O'nli kasrlarning sonlar nurida tasvirlanishi",
    "O'nli kasrlarni taqqoslash",
    "Foizlar",
    "Yo'lga sarflangan vaqtga doir masalalar",
    "III chorak bo'yicha takrorlash. Yakuniy test",
  ],
  g4_c4: [
    "O'qqa nisbatan simmetriya. Markazga nisbatan simmetriya",
    "Murakkab shakllar yuzi. Fraktallar",
    "To'g'ri burchakli parallelepiped, ko'pburchak va prizma",
    "Prizma va uning yoyilmasi",
    "Uchburchak va piramida",
    "Piramida va uning yoyilmasi",
    "Doira, shar va silindr",
    "Silindr va uning yoyilmasi",
    "Konus va uning yoyilmasi",
    "Fazoviy shakllarga doir masalalar",
    "Burchak turlari",
    "Burchakning o'lchovi. Gradus",
    "Burchakni transportir bilan o'lchash",
    "Burchakni transportir yordamida yasash",
    "Geometriyaga doir masalalar. Takrorlash",
    "IV chorak bo'yicha takrorlash. Yakuniy test",
  ],
};
